### ISSUE TITLE
Go to takes you to the next event you request

### ISSUE THREAD

**Issue by ikatza** [TITUS-EVD/gallery-framework#22]
Whenever I write an event number on the input box for `Go to` and press enter it takes me to the following event.

E.g:
- write 6
- punch enter
- --> takes me to event 7

**Comment by marcodeltutto** [comment]
Hi Iker, the `Go to` is basically just an index: it is zero-based, and always starts from zero. The `Event` number is the real event number, and while it usually starts from 1 creating the offset you see, in general it can start from whatever event number is in the first entry of the file. So the `Go to` is just an easier index to navigate through the file.

**Comment by marcodeltutto** [comment]
Closing this as `Go to` is replaced with a `Go` function that takes Run, SubRun, and Event numbers.

<img width="247" alt="image" src="https://github.com/user-attachments/assets/707cd952-ea6a-478a-8837-601eef4b101e">
