### ISSUE TITLE
Screen shot fails in 3D evd

### ISSUE THREAD

**Issue by marcodeltutto** [TITUS-EVD/gallery-framework#3]
The screen shot function in the 3D event display produced an image with a black square instead of the proper event display.

**Comment by coreyjadams** [comment]
This is a feature, not a bug!

I've seen this behavior for a long time, particularly on macs.  Is this on the gpvms or your laptop?  There is a problem with grabbing the screen when there are inconsistencies in the opengl set up, I think.  I have always just done a manual screenshot to get around this, but if it becomes a serious issue I can address it more head on.

**Comment by marcodeltutto** [comment]
lol
I am on the gpvm with a VNC server. Not a big issue in fact, I am taking a manual screenshot too.

**Comment by marcodeltutto** [comment]
Closing this as 3D viewer is addressed in #43
